### ISSUE TITLE
Best sampling Configuration

### ISSUE THREAD

**Issue by marrog86** [philippe44/squeezelite-esp32#23]
Hi,

I installed sucessfully your project and it works immediatly with bluetooth soundbar, thats real great work!!

Pleas could you explain the advantage of resampling, how do i now which configuration is the best for me? Im using LG SK5 Soundbar 

Whats the difference of Quality of BT, internal DAC and external DAC and is this differance noteable?  

Thanks

**Comment by philippe44** [comment]
I’m not sure I fully understand the question. 

When sending to a BT speaker, the only accepted sampling rate by the esp32 is 44.1 kHz (in theory 32 and 48 should work but they do not seem to). So you must use resampling either inside squeezelite-esp32 or ask LMS to do it. Internal sampling is probably lower quality than when done by LMS but it is unlikely audible when using BT.

When you use internal DAC, it’s a totally different configuration, it’s when you use my PCB that has an internal amplifier. So it is not usable when all you have is a WROVER module.

External DAC can be used with a WROVER standalone when you have connected it to an i2s DAC. But of course you need to connect the output of that DAC to your amplifier / soundbar

In term of quality, BT uses a lossy codec (AFAIR) to re-encode audio while i2s is the plain decoded audio  so it’s better quality. But I’m not sure you’ll hear such a difference.

You also have the spdif option, but maybe for another post
