### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by ole348** [philippe44/squeezelite-esp32#31]
Toolchain path: /home/ole/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: esp-2020r3
Compiler version: 8.4.0
Python requirements from /home/ole/esp/esp-idf/requirements.txt are satisfied.

App "squeezelite" version: v4.3-dev-2940-g6e776946d
CC build/squeezelite/output_i2s.o
In file included from /home/ole/esp/esp-idf/examples/squeezelite-esp32-master/components/squeezelite/squeezelite.h:286,
                 from /home/ole/esp/esp-idf/examples/squeezelite-esp32-master/components/squeezelite/output_i2s.c:43:
/home/ole/esp/esp-idf/examples/squeezelite-esp32-master/components/squeezelite/embedded.h:41:46: error: unknown type name '_CONST'
 int   pthread_create_name(pthread_t *thread, _CONST pthread_attr_t  *attr,
                                              ^~~~~~

**Comment by philippe44** [comment]
Please use esp-idf version 4.0
