### ISSUE TITLE
Add support for display

### ISSUE THREAD

**Issue by sle118** [philippe44/squeezelite-esp32#5]
Espressif has made littlevgl available of the platform.

https://github.com/espressif/esp-iot-solution/blob/master/documents/hmi_solution/littlevgl/littlevgl_guide_en.md

**Comment by daduke** [comment]
for the last 3 hours I tried setting up 'esp iot solution' and run a display test example. It does **not** compile using the 'new' tool chain (gcc 8.2). I can't find the 5.2 tool chain for Linux any longer and even if I could, I don't think that's the route to go. Any hints?

**Comment by philippe44** [comment]
you're talking about the specific display project, not about the squeezelite-esp32, right?

**Comment by daduke** [comment]
correct. squeezelite-esp32 compiles but stutters (you remember), but the "iot solution" which includes littleevgl throws hundreds of errors. I opened an issue https://github.com/espressif/esp-iot-solution/issues/51, let's see what they say.

**Comment by daduke** [comment]
ok I finally managed to install IDF 3.2 with gcc 5.2. Now the littleevgl examples do compile, but squeezelite-esp32 doesn't (nvs stuff unknown). Seems we can have either littleevgl or squeezelite-esp32, but not both. What a pain...

**Comment by sle118** [comment]
Let's keep this enhancement thread dedicated to the intended topic, please :)

**Comment by sle118** [comment]
Basic display for commonly available i2s oled screens has been implemented in sle118's repository, so closing this one.
